export const dom = {
    appContainer: document.getElementById('app-container'),
    tabsContainer: document.querySelector('.tabs'),
    fileTabBtn: document.getElementById('file-tab-btn'),
    textTabBtn: document.getElementById('text-tab-btn'),
    fileUploadView: document.getElementById('file-upload-view'),
    textPasteView: document.getElementById('text-paste-view'),
    dropzoneInput: document.getElementById('dropzone-file'),
    dropzoneLabel: document.querySelector('.dropzone'),
    fileNameDisplay: document.getElementById('file-name'),
    textInput: document.getElementById('text-input'),
    createFromTextBtn: document.getElementById('create-from-text-btn'),
    
    loader: document.getElementById('loader'),
    loaderProgress: document.getElementById('loader-progress'),
    loaderProgressText: document.getElementById('loader-progress-text'),
    errorDisplay: document.getElementById('error-display'),
    errorMessage: document.getElementById('error-message'),
    welcomeMessage: document.getElementById('welcome-message'),
    flipbookWrapper: document.getElementById('flipbook-wrapper'),
    flipbookEl: document.getElementById('flipbook'),
    prevPageBtn: document.getElementById('prev-page-btn'),
    nextPageBtn: document.getElementById('next-page-btn'),
    pageCounter: document.getElementById('page-counter'),
    createNewBtn: document.getElementById('create-new-btn'),
};